#!/bin/bash
if [[ -z "$DISPLAY" ]]; then
    echo "Error: \$DISPLAY not set, is Xorg in use?" >&2
    exit 1
fi

case "$1" in
    xv)
        out_typ="xv"
        pix_fmt="yuv420p"
        ;;
    sdl)
        out_typ="sdl"
        pix_fmt="bgr0"
        ;;
    *)
        out_typ="opengl"
        pix_fmt="bgr0"
        ;;
esac

ffmpeg \
    -f x11grab \
    -draw_mouse 1 \
    -framerate 2 \
    -grab_x 0 \
    -grab_y 0 \
    -video_size 1280x1080 \
    -i ${DISPLAY} \
    -pix_fmt ${pix_fmt} \
    -window_borderless true \
    -f ${out_typ} "'ffmpeg screen capture: ${out_typ}'" \
    -nostdin \
    -nostats \
    -loglevel 8 </dev/null >/dev/null 2>&1 &

sleep 1

process_pid=$(ps -C ffmpeg -o pid --no-heading)

if [ $process_pid ]; then 
    echo "Started ffmpeg Capture. PID: $process_pid"
else
    echo "Error: Not started" >&2
    exit 1
fi

exit 0
